// Generated by scripts/gen-content.mjs. Do not edit by hand.
// Regenerate with: pnpm gen:content
import type { Content } from './content.ts'

export const content: Content = {
  "root": {
    "name": "",
    "dirs": [
      {
        "name": "projects",
        "dirs": [],
        "files": [
          {
            "name": "knockport",
            "title": "knockport",
            "order": 1,
            "hidden": false,
            "body": "The thing you are typing into right now.\nA Rust core with no I/O, painted by an SSH server and a WebAssembly frontend.\nThe name is port knocking, and knocking on a door."
          }
        ]
      }
    ],
    "files": [
      {
        "name": "whoami",
        "title": "whoami",
        "order": 1,
        "hidden": false,
        "body": "Guillaume Flambard. Full-stack and AI engineer.\nFive years shipping products, the last three of them mostly alone,\nfrom the database up to whatever the user actually touches.\nFully remote, across European time zones."
      },
      {
        "name": "stack",
        "title": "stack",
        "order": 2,
        "hidden": false,
        "body": "Daily: TypeScript, React, Next.js, Laravel, PostgreSQL, Rust when it earns its place.\nAI: retrieval pipelines, agent orchestration, evaluation harnesses.\nInfra: Docker, nginx, Cloudflare, a VPS that has been up for 25 days."
      },
      {
        "name": "knock",
        "title": "knock",
        "order": 99,
        "hidden": true,
        "body": "You went looking. That is the whole test, and you passed it."
      }
    ]
  }
}
