// Generated by scripts/gen-content.mjs. Do not edit by hand.
// Regenerate with: pnpm gen:content
import type { Content } from './content.ts'

export const content: Content = {
  "root": {
    "name": "",
    "dirs": [
      {
        "name": "projects",
        "dirs": [],
        "files": [
          {
            "name": "knockport",
            "title": "knockport",
            "order": 1,
            "hidden": false,
            "body": "The thing you are typing into right now.\nA TypeScript core with no I/O, painted by an SSH server and a browser.\nThe name is port knocking, and knocking on a door."
          }
        ]
      }
    ],
    "files": [
      {
        "name": "whoami",
        "title": "who we are",
        "order": 1,
        "hidden": false,
        "body": "Memo Labs. A small product engineering company, registered in France.\nWe ship web products end to end and AI features that have to survive contact\nwith real users. Five years shipping, the last three of them as a company.\nFully remote, across European time zones."
      },
      {
        "name": "stack",
        "title": "what we build with",
        "order": 2,
        "hidden": false,
        "body": "Daily: TypeScript, React, Next.js, Laravel, PostgreSQL, Rust when it earns its place.\nAI: retrieval pipelines, agent orchestration, evaluation harnesses.\nInfra: Docker, nginx, Cloudflare, and a VPS we look after ourselves."
      },
      {
        "name": "knock",
        "title": "knock",
        "order": 99,
        "hidden": true,
        "body": "You went looking. That is the whole test, and you passed it.\nMention this file when you apply. It tells us more than a CV does."
      }
    ]
  }
}
