// Generated by scripts/gen-content.mjs. Do not edit by hand.
// Regenerate with: pnpm gen:content
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = fileURLToPath(new URL('..', import.meta.url))
const CONTENT_DIR = join(ROOT, 'content')
// Output path can be overridden, so the freshness test can generate
// elsewhere and compare without ever rewriting the tracked file.
const OUT = process.argv[2] ?? join(ROOT, 'packages/core/src/content.generated.ts')

const MAX_ORDER = Number.MAX_SAFE_INTEGER

function walk(dir) {
  const found = []
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) found.push(...walk(full))
    else if (entry.endsWith('.md')) found.push(full)
  }
  return found
}

/** Three fields, nothing else. Malformed frontmatter leaves all text in body. */
function parseFile(name, text) {
  const match = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/.exec(text)
  const fallback = { name, title: name, order: MAX_ORDER, hidden: false, body: text.trim() }
  if (!match) return fallback

  const fm = { title: undefined, order: undefined, hidden: false }
  for (const line of match[1].split(/\r?\n/)) {
    const kv = /^(title|order|hidden)\s*:\s*(.*)$/.exec(line.trim())
    if (!kv) continue
    const value = kv[2].trim().replace(/^["']|["']$/g, '')
    if (kv[1] === 'title') fm.title = value
    else if (kv[1] === 'order') {
      const n = Number.parseInt(value, 10)
      if (Number.isFinite(n) && n >= 0) fm.order = n
    } else fm.hidden = value === 'true'
  }

  return {
    name,
    title: fm.title ?? name,
    order: fm.order ?? MAX_ORDER,
    hidden: fm.hidden,
    body: text.slice(match[0].length).trim(),
  }
}

function insert(root, segments, file) {
  let cursor = root
  for (const segment of segments) {
    let next = cursor.dirs.find((d) => d.name === segment)
    if (!next) { next = { name: segment, dirs: [], files: [] }; cursor.dirs.push(next) }
    cursor = next
  }
  cursor.files.push(file)
}

/** Stable sort: by order ascending, then by name. Identical to the Rust sort. */
function sortDir(dir) {
  dir.files.sort((a, b) => a.order - b.order || (a.name < b.name ? -1 : a.name > b.name ? 1 : 0))
  dir.dirs.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0))
  dir.dirs.forEach(sortDir)
}

const root = { name: '', dirs: [], files: [] }
for (const path of walk(CONTENT_DIR)) {
  const rel = relative(CONTENT_DIR, path).split(/[\\/]/)
  const stem = rel.pop().replace(/\.md$/, '')
  insert(root, rel, parseFile(stem, readFileSync(path, 'utf8')))
}
sortDir(root)

writeFileSync(
  OUT,
  `// Generated by scripts/gen-content.mjs. Do not edit by hand.\n` +
    `// Regenerate with: pnpm gen:content\n` +
    `import type { Content } from './content.ts'\n\n` +
    `export const content: Content = ${JSON.stringify({ root }, null, 2)}\n`,
)
console.log(`content.generated.ts written, ${walk(CONTENT_DIR).length} files`)
